name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 3 * * *' # 9:00 AM IST everyday
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Playwright tests ${{ matrix.shardIndex }}/10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1,2,3,4,5,6,7,8,9,10]
        shardTotal: [10]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "TESTDINO_TOKEN=${{ secrets.TESTDINO_TOKEN }}" >> .env

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npm install file:testdino-playwright-10.11.tgz
          npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        env:
          TESTDINO_TOKEN: ${{ secrets.TESTDINO_TOKEN }}
          TESTDINO_SERVER_URL: https://staging-api.testdino.com
        run: |
          npx playwright test \
            --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload blob report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: ./blob-report
          retention-days: 1


  merge-reports:
    name: Merge Reports
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev @testdino/playwright@latest
          npx playwright install --with-deps

      - name: Download all blob reports
        uses: actions/download-artifact@v4
        with:
          path: ./all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge HTML & JSON reports
        run: |
          npx playwright merge-reports \
            --config=playwright.config.js \
            ./all-blob-reports

      - name: Upload combined Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: Playwright Test Report
          path: ./playwright-report
          retention-days: 14

      - name: Upload report to TestDino
        env:
          TESTDINO_TOKEN: ${{ secrets.TESTDINO_TOKEN }}
          TESTDINO_SERVER_URL: https://staging-api.testdino.com
        run: |
          npx tdpw upload ./playwright-report --token="$TESTDINO_TOKEN"